In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("C:/Users/chait/Python/Datasets/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df[df['Glucose']==0]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
75             1        0             48             20        0  24.7   
182            1        0             74             20       23  27.7   
342            1        0             68             35        0  32.0   
349            5        0             80             32        0  41.0   
502            6        0             68             41        0  39.0   

     DiabetesPedigreeFunction  Age  Outcome  
75                      0.140   22        0  
182                     0.299   21        0  
342                     0.389   22        0  
349                     0.346   37        1  
502                     0.727   41        1

In [7]:
df[df['Insulin']==0]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
..           ...      ...            ...            ...      ...   ...   
761            9      170             74             31        0  44.0   
762            9       89             62              0        0  22.5   
764            2      122             70             27        0  36.8   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
5                       0.201   30        0  
7                       0.134   29        0  
..                        ...  ...      ...  
761                     0.403   43        1  
762                     0.142   33        0  
764                     0.340   27        0  
766                     0.349   47        1  
767                     0.315   23        0  

[374 rows x 9 columns]

In [8]:
df[df['Age']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [9]:

df['Glucose']=np.where(df['Glucose']==0, df['Glucose'].median(),df['Glucose'])
df['Insulin']=np.where(df['Insulin']==0, df['Insulin'].median(),df['Insulin'])
df['SkinThickness']=np.where(df['SkinThickness']==0, df['SkinThickness'].median(),df['SkinThickness'])




In [10]:
df[df['Glucose']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [11]:
df[df['Insulin']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [12]:
df[df['SkinThickness']==0]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [13]:
# Independent and Dependent features
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [14]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [15]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [16]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.20, random_state=33)

X_train.shape, X_test.shape

((614, 8), (154, 8))

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf_classifier = RandomForestClassifier()

In [19]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier()

In [20]:
y_pred = rf_classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
      dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [22]:
print('Accuracy Score:\n',accuracy_score(y_test, y_pred))
print('Classifiaction Report:\n', classification_report(y_test, y_pred))
print('confusion Matrix:\n',confusion_matrix(y_test, y_pred))

Accuracy Score:
 0.7532467532467533
Classifiaction Report:
               precision    recall  f1-score   support

           0       0.77      0.87      0.82        99
           1       0.70      0.55      0.61        55

    accuracy                           0.75       154
   macro avg       0.74      0.71      0.72       154
weighted avg       0.75      0.75      0.75       154

confusion Matrix:
 [[86 13]
 [25 30]]


### Mannual Hyperparameter Tunning

In [100]:
rf = RandomForestClassifier(n_estimators=400, min_samples_split=10, min_samples_leaf=12, 
                            max_features='sqrt', criterion='entropy', random_state=50)

rf.fit(X_train, y_train)
pred = rf.predict(X_test)

accuracy_score(y_test, pred)

0.7532467532467533

### Randomized Serch CV

In [82]:
# Number of trees
n_estimators = [int(x) for x in np.linspace(200, 2000, 10)]

# Maximum number of features consider at every split
max_features = ['sqrt', 'log2', 'auto']

# Maximum number of level in tree
max_depth = [int(x) for x in np.linspace(10, 1000, 10)]

# Maximum sample required to split a node
min_sample_split = [1,4,8,12,14]

# Maximum samples requied at each leaf node
min_sample_leaf = [1,3,4,7,9]

# function used to eveluate the quality of split
criterion = ['gini', 'entropy']

param_grid = {
    'n_estimators' : n_estimators,
    'max_features' : max_features,
    'max_depth' : max_depth,
    'min_samples_split' : min_sample_split,
    'min_samples_leaf' : min_sample_leaf,
    'criterion' : criterion
}

print(param_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['sqrt', 'log2', 'auto'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [1, 4, 8, 12, 14], 'min_samples_leaf': [1, 3, 4, 7, 9], 'criterion': ['gini', 'entropy']}


In [83]:
from sklearn.model_selection import RandomizedSearchCV

In [84]:
rf = RandomForestClassifier()

In [85]:
rf_randomcv = RandomizedSearchCV(estimator=rf, 
                                param_distributions=param_grid,
                                n_iter=100,
                                cv=3,
                                verbose=2,
                                n_jobs=-1,
                                random_state=42)
print(rf_randomcv)

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['sqrt', 'log2',
                                                         'auto'],
                                        'min_samples_leaf': [1, 3, 4, 7, 9],
                                        'min_samples_split': [1, 4, 8, 12, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, verbose=2)


In [86]:
rf_randomcv.fit(X_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['sqrt', 'log2',
                                                         'auto'],
                                        'min_samples_leaf': [1, 3, 4, 7, 9],
                                        'min_samples_split': [1, 4, 8, 12, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, verbose=2)

In [87]:
rf_randomcv.best_params_

{'n_estimators': 1400,
 'min_samples_split': 4,
 'min_samples_leaf': 9,
 'max_features': 'log2',
 'max_depth': 10,
 'criterion': 'gini'}

In [88]:
rf_randomcv.best_estimator_

RandomForestClassifier(max_depth=10, max_features='log2', min_samples_leaf=9,
                       min_samples_split=4, n_estimators=1400)

In [89]:
best_grid = rf_randomcv.best_estimator_

In [90]:
prediction = best_grid.predict(X_test)

print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))

0.7337662337662337
              precision    recall  f1-score   support

           0       0.75      0.87      0.81        99
           1       0.68      0.49      0.57        55

    accuracy                           0.73       154
   macro avg       0.71      0.68      0.69       154
weighted avg       0.73      0.73      0.72       154

[[86 13]
 [28 27]]


### Grid Search CV

In [91]:
from sklearn.model_selection import GridSearchCV

In [92]:
rf_randomcv.best_params_

{'n_estimators': 1400,
 'min_samples_split': 4,
 'min_samples_leaf': 9,
 'max_features': 'log2',
 'max_depth': 10,
 'criterion': 'gini'}

In [93]:
space_grid = {
    'max_depth' : [rf_randomcv.best_params_['max_depth']],
    'max_features' : [rf_randomcv.best_params_['max_features']],
    'criterion' : [rf_randomcv.best_params_['criterion']],
    'n_estimators' : [rf_randomcv.best_params_['n_estimators'] - 300, rf_randomcv.best_params_['n_estimators'] - 75,
                     rf_randomcv.best_params_['n_estimators'],
                     rf_randomcv.best_params_['n_estimators'] + 200, rf_randomcv.best_params_['n_estimators'] + 300],
    'min_samples_split' : [rf_randomcv.best_params_['min_samples_split']- 2, 
                          rf_randomcv.best_params_['min_samples_split'] -1,
                          rf_randomcv.best_params_['min_samples_split'],
                          rf_randomcv.best_params_['min_samples_split'] + 6],
    'min_samples_leaf' : [rf_randomcv.best_params_['min_samples_leaf'] - 1, 
                         rf_randomcv.best_params_['min_samples_leaf'],
                         rf_randomcv.best_params_['min_samples_leaf'] + 3]

                                             
}
print(space_grid)

{'max_depth': [10], 'max_features': ['log2'], 'criterion': ['gini'], 'n_estimators': [1100, 1325, 1400, 1600, 1700], 'min_samples_split': [2, 3, 4, 10], 'min_samples_leaf': [8, 9, 12]}


In [94]:
gs_randomcv = GridSearchCV(estimator=rf,
                          param_grid=space_grid,
                          cv=3,
                          n_jobs=-1,
                          verbose=2)
print(gs_randomcv)

GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [10],
                         'max_features': ['log2'],
                         'min_samples_leaf': [8, 9, 12],
                         'min_samples_split': [2, 3, 4, 10],
                         'n_estimators': [1100, 1325, 1400, 1600, 1700]},
             verbose=2)


In [95]:
gs_randomcv.fit(X_train, y_train)

Fitting 3 folds for each of 60 candidates, totalling 180 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [10],
                         'max_features': ['log2'],
                         'min_samples_leaf': [8, 9, 12],
                         'min_samples_split': [2, 3, 4, 10],
                         'n_estimators': [1100, 1325, 1400, 1600, 1700]},
             verbose=2)

In [96]:
gs_randomcv.best_estimator_

RandomForestClassifier(max_depth=10, max_features='log2', min_samples_leaf=8,
                       n_estimators=1100)

In [97]:
best_gs_grid = gs_randomcv.best_estimator_

In [98]:
prediction1 = best_gs_grid.predict(X_test)

print(accuracy_score(y_test, prediction1))
print(classification_report(y_test, prediction1))
print(confusion_matrix(y_test, prediction1))

0.7337662337662337
              precision    recall  f1-score   support

           0       0.76      0.86      0.81        99
           1       0.67      0.51      0.58        55

    accuracy                           0.73       154
   macro avg       0.71      0.68      0.69       154
weighted avg       0.73      0.73      0.72       154

[[85 14]
 [27 28]]
